language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - 7

matrix:
  allow_failures:
    - php: hhvm
    - php: 7

before_script:
  - composer self-update
  - composer --dev install

script:
  - php ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run

after_script:
  - php vendor/bin/coveralls -v
